// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Version.proto

package SatDataCenter.DataExchange.TmTc;

public final class Version {
  private Version() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(Version.version);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ExchangeTopicType}
   */
  public enum ExchangeTopicType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNSPECIFIED_TYPE = 0;</code>
     */
    UNSPECIFIED_TYPE(0),
    /**
     * <code>TEST_FILE_TYPE = 1;</code>
     */
    TEST_FILE_TYPE(1),
    /**
     * <code>TEST_PARAMETER_FILE_TYPE = 2;</code>
     */
    TEST_PARAMETER_FILE_TYPE(2),
    /**
     * <code>TEST_DATA_TYPE = 3;</code>
     */
    TEST_DATA_TYPE(3),
    /**
     * <code>TEST_INTERPRETATION_TYPE = 4;</code>
     */
    TEST_INTERPRETATION_TYPE(4),
    /**
     * <code>TEST_ADJUST_TYPE = 5;</code>
     */
    TEST_ADJUST_TYPE(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNSPECIFIED_TYPE = 0;</code>
     */
    public static final int UNSPECIFIED_TYPE_VALUE = 0;
    /**
     * <code>TEST_FILE_TYPE = 1;</code>
     */
    public static final int TEST_FILE_TYPE_VALUE = 1;
    /**
     * <code>TEST_PARAMETER_FILE_TYPE = 2;</code>
     */
    public static final int TEST_PARAMETER_FILE_TYPE_VALUE = 2;
    /**
     * <code>TEST_DATA_TYPE = 3;</code>
     */
    public static final int TEST_DATA_TYPE_VALUE = 3;
    /**
     * <code>TEST_INTERPRETATION_TYPE = 4;</code>
     */
    public static final int TEST_INTERPRETATION_TYPE_VALUE = 4;
    /**
     * <code>TEST_ADJUST_TYPE = 5;</code>
     */
    public static final int TEST_ADJUST_TYPE_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ExchangeTopicType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ExchangeTopicType forNumber(int value) {
      switch (value) {
        case 0: return UNSPECIFIED_TYPE;
        case 1: return TEST_FILE_TYPE;
        case 2: return TEST_PARAMETER_FILE_TYPE;
        case 3: return TEST_DATA_TYPE;
        case 4: return TEST_INTERPRETATION_TYPE;
        case 5: return TEST_ADJUST_TYPE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ExchangeTopicType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ExchangeTopicType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ExchangeTopicType>() {
            public ExchangeTopicType findValueByNumber(int number) {
              return ExchangeTopicType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Version.getDescriptor().getEnumTypes().get(0);
    }

    private static final ExchangeTopicType[] VALUES = values();

    public static ExchangeTopicType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ExchangeTopicType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ExchangeTopicType)
  }

  /**
   * Protobuf enum {@code SubTopicName}
   */
  public enum SubTopicName
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUBTOPIC_UNSPECIFIED_TYPE = 0;</code>
     */
    SUBTOPIC_UNSPECIFIED_TYPE(0),
    /**
     * <code>DOCUMENT_TEST_TASK_REQUIREMENT = 1;</code>
     */
    DOCUMENT_TEST_TASK_REQUIREMENT(1),
    /**
     * <code>DOCUMENT_TEST_TASK_PLAN = 2;</code>
     */
    DOCUMENT_TEST_TASK_PLAN(2),
    /**
     * <code>DOCUMENT_TEST_TASK_EVALUATION_RESULT = 3;</code>
     */
    DOCUMENT_TEST_TASK_EVALUATION_RESULT(3),
    /**
     * <code>DATA_SAT_PHYVALUE = 4;</code>
     */
    DATA_SAT_PHYVALUE(4),
    /**
     * <pre>
     *参数表，每个分系统会有多张参数表，在head里只定义到分系统级，在数据区里定义到business_id   
     * </pre>
     *
     * <code>DATA_SUBSYSTEM_YCHL_PHYVALUE = 5;</code>
     */
    DATA_SUBSYSTEM_YCHL_PHYVALUE(5),
    /**
     * <code>DATA_SUBSYSTEM_XDMN_PHYVALUE = 6;</code>
     */
    DATA_SUBSYSTEM_XDMN_PHYVALUE(6),
    /**
     * <code>DATA_SUBSYSTEM_ZCDX_PHYVALUE = 7;</code>
     */
    DATA_SUBSYSTEM_ZCDX_PHYVALUE(7),
    /**
     * <code>DATA_SUBSYSTEM_CSCL_PHYVALUE = 8;</code>
     */
    DATA_SUBSYSTEM_CSCL_PHYVALUE(8),
    /**
     * <pre>
     *指令一张表，分系统指令通过指令号来划分
     * </pre>
     *
     * <code>DATA_TASK_CONTROL_INFO = 9;</code>
     */
    DATA_TASK_CONTROL_INFO(9),
    /**
     * <code>DATA_TASK_CONTROL_RESULT = 10;</code>
     */
    DATA_TASK_CONTROL_RESULT(10),
    /**
     * <code>INTERPRETATION_ALARM = 11;</code>
     */
    INTERPRETATION_ALARM(11),
    /**
     * <code>INTERPRETATION_RESULT_INFO = 12;</code>
     */
    INTERPRETATION_RESULT_INFO(12),
    /**
     * <code>ADJUST_TASK_SCHEDULE = 13;</code>
     */
    ADJUST_TASK_SCHEDULE(13),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SUBTOPIC_UNSPECIFIED_TYPE = 0;</code>
     */
    public static final int SUBTOPIC_UNSPECIFIED_TYPE_VALUE = 0;
    /**
     * <code>DOCUMENT_TEST_TASK_REQUIREMENT = 1;</code>
     */
    public static final int DOCUMENT_TEST_TASK_REQUIREMENT_VALUE = 1;
    /**
     * <code>DOCUMENT_TEST_TASK_PLAN = 2;</code>
     */
    public static final int DOCUMENT_TEST_TASK_PLAN_VALUE = 2;
    /**
     * <code>DOCUMENT_TEST_TASK_EVALUATION_RESULT = 3;</code>
     */
    public static final int DOCUMENT_TEST_TASK_EVALUATION_RESULT_VALUE = 3;
    /**
     * <code>DATA_SAT_PHYVALUE = 4;</code>
     */
    public static final int DATA_SAT_PHYVALUE_VALUE = 4;
    /**
     * <pre>
     *参数表，每个分系统会有多张参数表，在head里只定义到分系统级，在数据区里定义到business_id   
     * </pre>
     *
     * <code>DATA_SUBSYSTEM_YCHL_PHYVALUE = 5;</code>
     */
    public static final int DATA_SUBSYSTEM_YCHL_PHYVALUE_VALUE = 5;
    /**
     * <code>DATA_SUBSYSTEM_XDMN_PHYVALUE = 6;</code>
     */
    public static final int DATA_SUBSYSTEM_XDMN_PHYVALUE_VALUE = 6;
    /**
     * <code>DATA_SUBSYSTEM_ZCDX_PHYVALUE = 7;</code>
     */
    public static final int DATA_SUBSYSTEM_ZCDX_PHYVALUE_VALUE = 7;
    /**
     * <code>DATA_SUBSYSTEM_CSCL_PHYVALUE = 8;</code>
     */
    public static final int DATA_SUBSYSTEM_CSCL_PHYVALUE_VALUE = 8;
    /**
     * <pre>
     *指令一张表，分系统指令通过指令号来划分
     * </pre>
     *
     * <code>DATA_TASK_CONTROL_INFO = 9;</code>
     */
    public static final int DATA_TASK_CONTROL_INFO_VALUE = 9;
    /**
     * <code>DATA_TASK_CONTROL_RESULT = 10;</code>
     */
    public static final int DATA_TASK_CONTROL_RESULT_VALUE = 10;
    /**
     * <code>INTERPRETATION_ALARM = 11;</code>
     */
    public static final int INTERPRETATION_ALARM_VALUE = 11;
    /**
     * <code>INTERPRETATION_RESULT_INFO = 12;</code>
     */
    public static final int INTERPRETATION_RESULT_INFO_VALUE = 12;
    /**
     * <code>ADJUST_TASK_SCHEDULE = 13;</code>
     */
    public static final int ADJUST_TASK_SCHEDULE_VALUE = 13;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static SubTopicName valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SubTopicName forNumber(int value) {
      switch (value) {
        case 0: return SUBTOPIC_UNSPECIFIED_TYPE;
        case 1: return DOCUMENT_TEST_TASK_REQUIREMENT;
        case 2: return DOCUMENT_TEST_TASK_PLAN;
        case 3: return DOCUMENT_TEST_TASK_EVALUATION_RESULT;
        case 4: return DATA_SAT_PHYVALUE;
        case 5: return DATA_SUBSYSTEM_YCHL_PHYVALUE;
        case 6: return DATA_SUBSYSTEM_XDMN_PHYVALUE;
        case 7: return DATA_SUBSYSTEM_ZCDX_PHYVALUE;
        case 8: return DATA_SUBSYSTEM_CSCL_PHYVALUE;
        case 9: return DATA_TASK_CONTROL_INFO;
        case 10: return DATA_TASK_CONTROL_RESULT;
        case 11: return INTERPRETATION_ALARM;
        case 12: return INTERPRETATION_RESULT_INFO;
        case 13: return ADJUST_TASK_SCHEDULE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SubTopicName>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SubTopicName> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SubTopicName>() {
            public SubTopicName findValueByNumber(int number) {
              return SubTopicName.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return Version.getDescriptor().getEnumTypes().get(1);
    }

    private static final SubTopicName[] VALUES = values();

    public static SubTopicName valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SubTopicName(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SubTopicName)
  }

  public interface ProtoHeadInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoHeadInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *主题类型，文件类，试验参数类，试验数据类，判读数据类，导调类     TEST_DATA_TYPE
     * </pre>
     *
     * <code>.ExchangeTopicType topic_type = 1;</code>
     * @return The enum numeric value on the wire for topicType.
     */
    int getTopicTypeValue();
    /**
     * <pre>
     *主题类型，文件类，试验参数类，试验数据类，判读数据类，导调类     TEST_DATA_TYPE
     * </pre>
     *
     * <code>.ExchangeTopicType topic_type = 1;</code>
     * @return The topicType.
     */
    ExchangeTopicType getTopicType();

    /**
     * <pre>
     *子主题--名          卫星DATA_SAT_PHYVALUE和设备DATA_SUBSYSTEM_CSCL_PHYVALUE
     * </pre>
     *
     * <code>.SubTopicName bussiness = 2;</code>
     * @return The enum numeric value on the wire for bussiness.
     */
    int getBussinessValue();
    /**
     * <pre>
     *子主题--名          卫星DATA_SAT_PHYVALUE和设备DATA_SUBSYSTEM_CSCL_PHYVALUE
     * </pre>
     *
     * <code>.SubTopicName bussiness = 2;</code>
     * @return The bussiness.
     */
    SubTopicName getBussiness();

    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp msg_time = 4;</code>
     * @return Whether the msgTime field is set.
     */
    boolean hasMsgTime();
    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp msg_time = 4;</code>
     * @return The msgTime.
     */
    com.google.protobuf.Timestamp getMsgTime();
    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp msg_time = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getMsgTimeOrBuilder();

    /**
     * <pre>
     * 任务id             试验任务id
     * </pre>
     *
     * <code>string task_id = 5;</code>
     * @return The taskId.
     */
    String getTaskId();
    /**
     * <pre>
     * 任务id             试验任务id
     * </pre>
     *
     * <code>string task_id = 5;</code>
     * @return The bytes for taskId.
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <pre>
     *消息来源         数据处理
     * </pre>
     *
     * <code>string msg_source = 6;</code>
     * @return The msgSource.
     */
    String getMsgSource();
    /**
     * <pre>
     *消息来源         数据处理
     * </pre>
     *
     * <code>string msg_source = 6;</code>
     * @return The bytes for msgSource.
     */
    com.google.protobuf.ByteString
        getMsgSourceBytes();
  }
  /**
   * Protobuf type {@code ProtoHeadInfo}
   */
  public static final class ProtoHeadInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtoHeadInfo)
      ProtoHeadInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoHeadInfo.newBuilder() to construct.
    private ProtoHeadInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoHeadInfo() {
      topicType_ = 0;
      bussiness_ = 0;
      taskId_ = "";
      msgSource_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtoHeadInfo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoHeadInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              topicType_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              bussiness_ = rawValue;
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (msgTime_ != null) {
                subBuilder = msgTime_.toBuilder();
              }
              msgTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msgTime_);
                msgTime_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              taskId_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              msgSource_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Version.internal_static_ProtoHeadInfo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Version.internal_static_ProtoHeadInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoHeadInfo.class, Builder.class);
    }

    public static final int TOPIC_TYPE_FIELD_NUMBER = 1;
    private int topicType_;
    /**
     * <pre>
     *主题类型，文件类，试验参数类，试验数据类，判读数据类，导调类     TEST_DATA_TYPE
     * </pre>
     *
     * <code>.ExchangeTopicType topic_type = 1;</code>
     * @return The enum numeric value on the wire for topicType.
     */
    @Override public int getTopicTypeValue() {
      return topicType_;
    }
    /**
     * <pre>
     *主题类型，文件类，试验参数类，试验数据类，判读数据类，导调类     TEST_DATA_TYPE
     * </pre>
     *
     * <code>.ExchangeTopicType topic_type = 1;</code>
     * @return The topicType.
     */
    @Override public ExchangeTopicType getTopicType() {
      @SuppressWarnings("deprecation")
      ExchangeTopicType result = ExchangeTopicType.valueOf(topicType_);
      return result == null ? ExchangeTopicType.UNRECOGNIZED : result;
    }

    public static final int BUSSINESS_FIELD_NUMBER = 2;
    private int bussiness_;
    /**
     * <pre>
     *子主题--名          卫星DATA_SAT_PHYVALUE和设备DATA_SUBSYSTEM_CSCL_PHYVALUE
     * </pre>
     *
     * <code>.SubTopicName bussiness = 2;</code>
     * @return The enum numeric value on the wire for bussiness.
     */
    @Override public int getBussinessValue() {
      return bussiness_;
    }
    /**
     * <pre>
     *子主题--名          卫星DATA_SAT_PHYVALUE和设备DATA_SUBSYSTEM_CSCL_PHYVALUE
     * </pre>
     *
     * <code>.SubTopicName bussiness = 2;</code>
     * @return The bussiness.
     */
    @Override public SubTopicName getBussiness() {
      @SuppressWarnings("deprecation")
      SubTopicName result = SubTopicName.valueOf(bussiness_);
      return result == null ? SubTopicName.UNRECOGNIZED : result;
    }

    public static final int MSG_TIME_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp msgTime_;
    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp msg_time = 4;</code>
     * @return Whether the msgTime field is set.
     */
    @Override
    public boolean hasMsgTime() {
      return msgTime_ != null;
    }
    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp msg_time = 4;</code>
     * @return The msgTime.
     */
    @Override
    public com.google.protobuf.Timestamp getMsgTime() {
      return msgTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : msgTime_;
    }
    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp msg_time = 4;</code>
     */
    @Override
    public com.google.protobuf.TimestampOrBuilder getMsgTimeOrBuilder() {
      return getMsgTime();
    }

    public static final int TASK_ID_FIELD_NUMBER = 5;
    private volatile Object taskId_;
    /**
     * <pre>
     * 任务id             试验任务id
     * </pre>
     *
     * <code>string task_id = 5;</code>
     * @return The taskId.
     */
    @Override
    public String getTaskId() {
      Object ref = taskId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 任务id             试验任务id
     * </pre>
     *
     * <code>string task_id = 5;</code>
     * @return The bytes for taskId.
     */
    @Override
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_SOURCE_FIELD_NUMBER = 6;
    private volatile Object msgSource_;
    /**
     * <pre>
     *消息来源         数据处理
     * </pre>
     *
     * <code>string msg_source = 6;</code>
     * @return The msgSource.
     */
    @Override
    public String getMsgSource() {
      Object ref = msgSource_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgSource_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息来源         数据处理
     * </pre>
     *
     * <code>string msg_source = 6;</code>
     * @return The bytes for msgSource.
     */
    @Override
    public com.google.protobuf.ByteString
        getMsgSourceBytes() {
      Object ref = msgSource_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (topicType_ != ExchangeTopicType.UNSPECIFIED_TYPE.getNumber()) {
        output.writeEnum(1, topicType_);
      }
      if (bussiness_ != SubTopicName.SUBTOPIC_UNSPECIFIED_TYPE.getNumber()) {
        output.writeEnum(2, bussiness_);
      }
      if (msgTime_ != null) {
        output.writeMessage(4, getMsgTime());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, taskId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgSource_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, msgSource_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (topicType_ != ExchangeTopicType.UNSPECIFIED_TYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, topicType_);
      }
      if (bussiness_ != SubTopicName.SUBTOPIC_UNSPECIFIED_TYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, bussiness_);
      }
      if (msgTime_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getMsgTime());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(taskId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, taskId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgSource_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, msgSource_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoHeadInfo)) {
        return super.equals(obj);
      }
      ProtoHeadInfo other = (ProtoHeadInfo) obj;

      if (topicType_ != other.topicType_) return false;
      if (bussiness_ != other.bussiness_) return false;
      if (hasMsgTime() != other.hasMsgTime()) return false;
      if (hasMsgTime()) {
        if (!getMsgTime()
            .equals(other.getMsgTime())) return false;
      }
      if (!getTaskId()
          .equals(other.getTaskId())) return false;
      if (!getMsgSource()
          .equals(other.getMsgSource())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOPIC_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + topicType_;
      hash = (37 * hash) + BUSSINESS_FIELD_NUMBER;
      hash = (53 * hash) + bussiness_;
      if (hasMsgTime()) {
        hash = (37 * hash) + MSG_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getMsgTime().hashCode();
      }
      hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      hash = (37 * hash) + MSG_SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgSource().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoHeadInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoHeadInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoHeadInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoHeadInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoHeadInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoHeadInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoHeadInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoHeadInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoHeadInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoHeadInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoHeadInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoHeadInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoHeadInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoHeadInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoHeadInfo)
        ProtoHeadInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Version.internal_static_ProtoHeadInfo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Version.internal_static_ProtoHeadInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoHeadInfo.class, Builder.class);
      }

      // Construct using SatDataCenter.DataExchange.TmTc.Version.ProtoHeadInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        topicType_ = 0;

        bussiness_ = 0;

        if (msgTimeBuilder_ == null) {
          msgTime_ = null;
        } else {
          msgTime_ = null;
          msgTimeBuilder_ = null;
        }
        taskId_ = "";

        msgSource_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Version.internal_static_ProtoHeadInfo_descriptor;
      }

      @Override
      public ProtoHeadInfo getDefaultInstanceForType() {
        return ProtoHeadInfo.getDefaultInstance();
      }

      @Override
      public ProtoHeadInfo build() {
        ProtoHeadInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ProtoHeadInfo buildPartial() {
        ProtoHeadInfo result = new ProtoHeadInfo(this);
        result.topicType_ = topicType_;
        result.bussiness_ = bussiness_;
        if (msgTimeBuilder_ == null) {
          result.msgTime_ = msgTime_;
        } else {
          result.msgTime_ = msgTimeBuilder_.build();
        }
        result.taskId_ = taskId_;
        result.msgSource_ = msgSource_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoHeadInfo) {
          return mergeFrom((ProtoHeadInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoHeadInfo other) {
        if (other == ProtoHeadInfo.getDefaultInstance()) return this;
        if (other.topicType_ != 0) {
          setTopicTypeValue(other.getTopicTypeValue());
        }
        if (other.bussiness_ != 0) {
          setBussinessValue(other.getBussinessValue());
        }
        if (other.hasMsgTime()) {
          mergeMsgTime(other.getMsgTime());
        }
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        if (!other.getMsgSource().isEmpty()) {
          msgSource_ = other.msgSource_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoHeadInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoHeadInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int topicType_ = 0;
      /**
       * <pre>
       *主题类型，文件类，试验参数类，试验数据类，判读数据类，导调类     TEST_DATA_TYPE
       * </pre>
       *
       * <code>.ExchangeTopicType topic_type = 1;</code>
       * @return The enum numeric value on the wire for topicType.
       */
      @Override public int getTopicTypeValue() {
        return topicType_;
      }
      /**
       * <pre>
       *主题类型，文件类，试验参数类，试验数据类，判读数据类，导调类     TEST_DATA_TYPE
       * </pre>
       *
       * <code>.ExchangeTopicType topic_type = 1;</code>
       * @param value The enum numeric value on the wire for topicType to set.
       * @return This builder for chaining.
       */
      public Builder setTopicTypeValue(int value) {
        
        topicType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主题类型，文件类，试验参数类，试验数据类，判读数据类，导调类     TEST_DATA_TYPE
       * </pre>
       *
       * <code>.ExchangeTopicType topic_type = 1;</code>
       * @return The topicType.
       */
      @Override
      public ExchangeTopicType getTopicType() {
        @SuppressWarnings("deprecation")
        ExchangeTopicType result = ExchangeTopicType.valueOf(topicType_);
        return result == null ? ExchangeTopicType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *主题类型，文件类，试验参数类，试验数据类，判读数据类，导调类     TEST_DATA_TYPE
       * </pre>
       *
       * <code>.ExchangeTopicType topic_type = 1;</code>
       * @param value The topicType to set.
       * @return This builder for chaining.
       */
      public Builder setTopicType(ExchangeTopicType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        topicType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *主题类型，文件类，试验参数类，试验数据类，判读数据类，导调类     TEST_DATA_TYPE
       * </pre>
       *
       * <code>.ExchangeTopicType topic_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopicType() {
        
        topicType_ = 0;
        onChanged();
        return this;
      }

      private int bussiness_ = 0;
      /**
       * <pre>
       *子主题--名          卫星DATA_SAT_PHYVALUE和设备DATA_SUBSYSTEM_CSCL_PHYVALUE
       * </pre>
       *
       * <code>.SubTopicName bussiness = 2;</code>
       * @return The enum numeric value on the wire for bussiness.
       */
      @Override public int getBussinessValue() {
        return bussiness_;
      }
      /**
       * <pre>
       *子主题--名          卫星DATA_SAT_PHYVALUE和设备DATA_SUBSYSTEM_CSCL_PHYVALUE
       * </pre>
       *
       * <code>.SubTopicName bussiness = 2;</code>
       * @param value The enum numeric value on the wire for bussiness to set.
       * @return This builder for chaining.
       */
      public Builder setBussinessValue(int value) {
        
        bussiness_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *子主题--名          卫星DATA_SAT_PHYVALUE和设备DATA_SUBSYSTEM_CSCL_PHYVALUE
       * </pre>
       *
       * <code>.SubTopicName bussiness = 2;</code>
       * @return The bussiness.
       */
      @Override
      public SubTopicName getBussiness() {
        @SuppressWarnings("deprecation")
        SubTopicName result = SubTopicName.valueOf(bussiness_);
        return result == null ? SubTopicName.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *子主题--名          卫星DATA_SAT_PHYVALUE和设备DATA_SUBSYSTEM_CSCL_PHYVALUE
       * </pre>
       *
       * <code>.SubTopicName bussiness = 2;</code>
       * @param value The bussiness to set.
       * @return This builder for chaining.
       */
      public Builder setBussiness(SubTopicName value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        bussiness_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *子主题--名          卫星DATA_SAT_PHYVALUE和设备DATA_SUBSYSTEM_CSCL_PHYVALUE
       * </pre>
       *
       * <code>.SubTopicName bussiness = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBussiness() {
        
        bussiness_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp msgTime_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> msgTimeBuilder_;
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp msg_time = 4;</code>
       * @return Whether the msgTime field is set.
       */
      public boolean hasMsgTime() {
        return msgTimeBuilder_ != null || msgTime_ != null;
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp msg_time = 4;</code>
       * @return The msgTime.
       */
      public com.google.protobuf.Timestamp getMsgTime() {
        if (msgTimeBuilder_ == null) {
          return msgTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : msgTime_;
        } else {
          return msgTimeBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp msg_time = 4;</code>
       */
      public Builder setMsgTime(com.google.protobuf.Timestamp value) {
        if (msgTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgTime_ = value;
          onChanged();
        } else {
          msgTimeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp msg_time = 4;</code>
       */
      public Builder setMsgTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (msgTimeBuilder_ == null) {
          msgTime_ = builderForValue.build();
          onChanged();
        } else {
          msgTimeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp msg_time = 4;</code>
       */
      public Builder mergeMsgTime(com.google.protobuf.Timestamp value) {
        if (msgTimeBuilder_ == null) {
          if (msgTime_ != null) {
            msgTime_ =
              com.google.protobuf.Timestamp.newBuilder(msgTime_).mergeFrom(value).buildPartial();
          } else {
            msgTime_ = value;
          }
          onChanged();
        } else {
          msgTimeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp msg_time = 4;</code>
       */
      public Builder clearMsgTime() {
        if (msgTimeBuilder_ == null) {
          msgTime_ = null;
          onChanged();
        } else {
          msgTime_ = null;
          msgTimeBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp msg_time = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getMsgTimeBuilder() {
        
        onChanged();
        return getMsgTimeFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp msg_time = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getMsgTimeOrBuilder() {
        if (msgTimeBuilder_ != null) {
          return msgTimeBuilder_.getMessageOrBuilder();
        } else {
          return msgTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : msgTime_;
        }
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>.google.protobuf.Timestamp msg_time = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getMsgTimeFieldBuilder() {
        if (msgTimeBuilder_ == null) {
          msgTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getMsgTime(),
                  getParentForChildren(),
                  isClean());
          msgTime_ = null;
        }
        return msgTimeBuilder_;
      }

      private Object taskId_ = "";
      /**
       * <pre>
       * 任务id             试验任务id
       * </pre>
       *
       * <code>string task_id = 5;</code>
       * @return The taskId.
       */
      public String getTaskId() {
        Object ref = taskId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 任务id             试验任务id
       * </pre>
       *
       * <code>string task_id = 5;</code>
       * @return The bytes for taskId.
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 任务id             试验任务id
       * </pre>
       *
       * <code>string task_id = 5;</code>
       * @param value The taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务id             试验任务id
       * </pre>
       *
       * <code>string task_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 任务id             试验任务id
       * </pre>
       *
       * <code>string task_id = 5;</code>
       * @param value The bytes for taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskId_ = value;
        onChanged();
        return this;
      }

      private Object msgSource_ = "";
      /**
       * <pre>
       *消息来源         数据处理
       * </pre>
       *
       * <code>string msg_source = 6;</code>
       * @return The msgSource.
       */
      public String getMsgSource() {
        Object ref = msgSource_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgSource_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *消息来源         数据处理
       * </pre>
       *
       * <code>string msg_source = 6;</code>
       * @return The bytes for msgSource.
       */
      public com.google.protobuf.ByteString
          getMsgSourceBytes() {
        Object ref = msgSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息来源         数据处理
       * </pre>
       *
       * <code>string msg_source = 6;</code>
       * @param value The msgSource to set.
       * @return This builder for chaining.
       */
      public Builder setMsgSource(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgSource_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息来源         数据处理
       * </pre>
       *
       * <code>string msg_source = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgSource() {
        
        msgSource_ = getDefaultInstance().getMsgSource();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息来源         数据处理
       * </pre>
       *
       * <code>string msg_source = 6;</code>
       * @param value The bytes for msgSource to set.
       * @return This builder for chaining.
       */
      public Builder setMsgSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgSource_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProtoHeadInfo)
    }

    // @@protoc_insertion_point(class_scope:ProtoHeadInfo)
    private static final ProtoHeadInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoHeadInfo();
    }

    public static ProtoHeadInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoHeadInfo>
        PARSER = new com.google.protobuf.AbstractParser<ProtoHeadInfo>() {
      @Override
      public ProtoHeadInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoHeadInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoHeadInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProtoHeadInfo> getParserForType() {
      return PARSER;
    }

    @Override
    public ProtoHeadInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int VERSION_FIELD_NUMBER = 50001;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      String> version = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        String.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoHeadInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoHeadInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rVersion.proto\032 google/protobuf/descrip" +
      "tor.proto\032\037google/protobuf/timestamp.pro" +
      "to\"\254\001\n\rProtoHeadInfo\022&\n\ntopic_type\030\001 \001(\016" +
      "2\022.ExchangeTopicType\022 \n\tbussiness\030\002 \001(\0162" +
      "\r.SubTopicName\022,\n\010msg_time\030\004 \001(\0132\032.googl" +
      "e.protobuf.Timestamp\022\017\n\007task_id\030\005 \001(\t\022\022\n" +
      "\nmsg_source\030\006 \001(\t*\243\001\n\021ExchangeTopicType\022" +
      "\024\n\020UNSPECIFIED_TYPE\020\000\022\022\n\016TEST_FILE_TYPE\020" +
      "\001\022\034\n\030TEST_PARAMETER_FILE_TYPE\020\002\022\022\n\016TEST_" +
      "DATA_TYPE\020\003\022\034\n\030TEST_INTERPRETATION_TYPE\020" +
      "\004\022\024\n\020TEST_ADJUST_TYPE\020\005*\305\003\n\014SubTopicName" +
      "\022\035\n\031SUBTOPIC_UNSPECIFIED_TYPE\020\000\022\"\n\036DOCUM" +
      "ENT_TEST_TASK_REQUIREMENT\020\001\022\033\n\027DOCUMENT_" +
      "TEST_TASK_PLAN\020\002\022(\n$DOCUMENT_TEST_TASK_E" +
      "VALUATION_RESULT\020\003\022\025\n\021DATA_SAT_PHYVALUE\020" +
      "\004\022 \n\034DATA_SUBSYSTEM_YCHL_PHYVALUE\020\005\022 \n\034D" +
      "ATA_SUBSYSTEM_XDMN_PHYVALUE\020\006\022 \n\034DATA_SU" +
      "BSYSTEM_ZCDX_PHYVALUE\020\007\022 \n\034DATA_SUBSYSTE" +
      "M_CSCL_PHYVALUE\020\010\022\032\n\026DATA_TASK_CONTROL_I" +
      "NFO\020\t\022\034\n\030DATA_TASK_CONTROL_RESULT\020\n\022\030\n\024I" +
      "NTERPRETATION_ALARM\020\013\022\036\n\032INTERPRETATION_" +
      "RESULT_INFO\020\014\022\030\n\024ADJUST_TASK_SCHEDULE\020\r:" +
      "5\n\007version\022\037.google.protobuf.MessageOpti" +
      "ons\030\321\206\003 \001(\t\210\001\001BC\n\037SatDataCenter.DataExch" +
      "ange.TmTc\252\002\037SatDataCenter.DataExchange.T" +
      "mTcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_ProtoHeadInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoHeadInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoHeadInfo_descriptor,
        new String[] { "TopicType", "Bussiness", "MsgTime", "TaskId", "MsgSource", });
    version.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.DescriptorProtos.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
